<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.erano01</groupId>
        <artifactId>EranoAPI-NMS</artifactId>
        <version>1.0.0-alpha.2</version>
    </parent>

    <artifactId>V1_8_R2</artifactId>

    <dependencies>
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot</artifactId>
            <version>1.8.3-R0.1-SNAPSHOT</version>
            <!-- Provided olmalı eğer localdan çalıştırcaksan, birde root pom.xml de github'dan çekiyor nms dependencyleri -->
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <includes>
                    <include>META-INF/**</include>
                </includes>
            </resource>
        </resources>
    </build>
</project>