name: EranoAPI
version: ${project.version}
main: me.erano.com.api.CorePlugin
#api-version can be 1.13 min
api-version: 1.13
commands:
  showTPS:
    description: Shows the current TPS
  piano:
    description: open piano
    usage: /piano
  eranodemo:
    description: Try the action bar, title and hologram services
    usage: /eranodemo <actionbar|title|holo|unholo>
    permission: eranoapi.demo
permissions:
  eranoapi.demo:
    default: op
