"""Writes EranoAPI's material API data: the EranoMaterial enum's constants and its tables (materials.tsv, legacy.tsv),
from the same dumps as report.py (out/<version>.tsv, legacy-1.13.2.tsv, analysis.json) and its renames."""
import json,os,sys
sys.path.insert(0,os.path.dirname(os.path.abspath(__file__)))
core=sys.argv[1]
a=json.load(open('analysis.json'))
newest=a['versions'][-1]
RENAMES=[('CACTUS_GREEN','GREEN_DYE'),('DANDELION_YELLOW','YELLOW_DYE'),('ROSE_RED','RED_DYE'),('SIGN','OAK_SIGN'),
('WALL_SIGN','OAK_WALL_SIGN'),('ZOMBIE_PIGMAN_SPAWN_EGG','ZOMBIFIED_PIGLIN_SPAWN_EGG'),('GRASS_PATH','DIRT_PATH'),
('POTTERY_SHARD_ARCHER','ARCHER_POTTERY_SHERD'),('POTTERY_SHARD_ARMS_UP','ARMS_UP_POTTERY_SHERD'),
('POTTERY_SHARD_PRIZE','PRIZE_POTTERY_SHERD'),('POTTERY_SHARD_SKULL','SKULL_POTTERY_SHERD'),('GRASS','SHORT_GRASS'),
('SCUTE','TURTLE_SCUTE'),('CHAIN','IRON_CHAIN')]
new_of=dict(RENAMES)
def today(n):
    while n in new_of: n=new_of[n]
    return n
old_names={}
for o,n in RENAMES:
    old_names.setdefault(today(n),[]).insert(0,o)  # newest first
# Newest server's names, in its order.
names=[l.split('\t')[0] for l in open('out/%s.tsv'%newest) if not l.startswith('#') and l.strip()]
names=[n for n in names if not n.startswith('LEGACY_')]
known=set(names)
legacy_rows=[l.rstrip('\n').split('\t') for l in open('legacy-1.13.2.tsv')]
forward=[]; inverse={}
for pass_ in ('item','block'):
    for name,id_,data,block,item,isb,isi in legacy_rows:
        result=item if pass_=='item' and isi=='1' else block if pass_=='block' and isb=='1' else None
        if not result or result=='AIR' and name!='AIR':
            continue
        if name=='MONSTER_EGG' and data=='0':
            # The 1.13 converter calls an egg without an entity a pig's; on 1.8 it spawns nothing (the pig is 90).
            continue
        t=today(result)
        if t not in inverse:
            inverse[t]=(name,int(data))
for name,id_,data,block,item,isb,isi in legacy_rows:
    b=today(block) if isb=='1' and block!='AIR' else ''
    i=today(item) if isi=='1' and item!='AIR' else ''
    if name=='AIR': b=i='AIR'
    if b or i:
        forward.append((name,int(data),b,i))
missing=[n for n in inverse if n not in known]
assert not missing, missing
res=os.path.join(core,'src/main/resources/eranoapi/material'); os.makedirs(res,exist_ok=True)
with open(os.path.join(res,'materials.tsv'),'w') as f:
    f.write('# name\tlegacy name (1.8 - 1.12)\tlegacy data\tolder names, newest first. Generated by scripts/material-report/generate.py\n')
    for n in names:
        ln,ld=inverse.get(n,('',0))
        f.write('%s\t%s\t%s\t%s\n'%(n,ln,ld if ln else '',','.join(old_names.get(n,[]))))
with open(os.path.join(res,'legacy.tsv'),'w') as f:
    f.write('# legacy name\tdata\tas a block\tas an item (today\'s names). Generated by scripts/material-report/generate.py\n')
    for name,data,b,i in forward:
        f.write('%s\t%d\t%s\t%s\n'%(name,data,b,i))
# The enum's constants.
src=os.path.join(core,'src/main/java/me/erano/com/api/material/EranoMaterial.java')
body=open(src).read() if os.path.exists(src) else None
consts=',\n'.join('    '+n for n in names)+';'
start='    // <generated constants>'; end='    // </generated constants>'
if body and start in body:
    i=body.index(start)+len(start); j=body.index(end)
    body=body[:i]+'\n'+consts+'\n'+body[j:]
    open(src,'w').write(body)
print('materials',len(names),'with legacy',len(inverse),'renamed',len(old_names),'legacy rows',len(forward))
