org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=true

org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.configuration-cache.problems=warn

net.minecraftforge.gradle.merge-source-sets=true

# <EranoAPI version>+<Minecraft version>
mod_version=1.0.0+26.3
minecraft_version=26.3
minecraft_version_range=[26.3,26.4)
forge_version=66.0.9
forge_version_range=[66,)
eventbus_validator_version=7.0.6
# EranoAPI-Common, installed into ~/.m2 by `mvn install` in the repository root
eranoapi_common_version=1.0.0
